framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
